# This file configures the static analysis results for your project (errors,
# warnings, and lints).
#
# This enables the 'recommended' set of lints from `package:lints`.
# This set helps identify many issues that may lead to problems when running
# or consuming Dart code, and enforces writing Dart using a single, idiomatic
# style and format.
#
# If you want a smaller set of lints you can change this to specify
# 'package:lints/core.yaml'. These are just the most critical lints
# (the recommended set includes the core lints).
# The core lints are also what is used by pub.dev for scoring packages.

include: package:lints/recommended.yaml

linter:
  rules:
    # avoid_print: false  # Uncomment to disable the `avoid_print` rule

    # string style
    prefer_single_quotes: true
    prefer_double_quotes: false
    avoid_escaping_inner_quotes: true
    use_raw_strings: true

    # import statements
    always_use_package_imports: true
    prefer_relative_imports: false

    # variables
    unnecessary_final: true
    avoid_final_parameters: true
    parameter_assignments: true
    prefer_final_fields: true
    prefer_final_parameters: false
    prefer_final_locals: false
    prefer_final_in_for_each: false
    prefer_function_declarations_over_variables: false

    # types
    always_specify_types: false
    avoid_types_on_closure_parameters: false
    omit_local_variable_types: true

    # containers
    use_colored_box: true
    use_decorated_box: true

    # sort constructors
    sort_constructors_first: true
    sort_unnamed_constructors_first: true

    # other rules
    avoid_equals_and_hash_code_on_mutable_classes: false
    avoid_dynamic_calls: true
    avoid_slow_async_io: true
    avoid_type_to_string: true
    comment_references: true
    discarded_futures: true
    no_adjacent_strings_in_list: true
    test_types_in_equals: true
    always_declare_return_types: true
    always_put_control_body_on_new_line: false
    always_put_required_named_parameters_first: true
    avoid_annotating_with_dynamic: false
    avoid_catches_without_on_clauses: true
    avoid_classes_with_only_static_members: true
    avoid_double_and_int_checks: true
    avoid_field_initializers_in_const_classes: true
    avoid_implementing_value_types: true
    avoid_positional_boolean_parameters: true
    avoid_void_async: true
    cascade_invocations: true
    cast_nullable_to_non_nullable: true
    directives_ordering: true
    eol_at_end_of_file: true
    leading_newlines_in_multiline_strings: true
    missing_whitespace_between_adjacent_strings: true
    noop_primitive_operations: true
    one_member_abstracts: true
    only_throw_errors: true
    prefer_constructors_over_static_methods: true
    prefer_expression_function_bodies: true
    prefer_foreach: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_mixin: true
    prefer_null_aware_method_calls: true
    sized_box_shrink_expand: true
    type_annotate_public_apis: true
    unawaited_futures: true
    unnecessary_await_in_return: true
    unnecessary_lambdas: true
    unnecessary_null_checks: true
    unnecessary_to_list_in_spreads: true
    use_enums: true
    use_if_null_to_convert_nulls_to_bools: true
    use_is_even_rather_than_modulo: true
    use_late_for_private_fields_and_variables: true
    use_named_constants: true
    use_setters_to_change_properties: true
    use_string_buffers: true
    use_super_parameters: true
    use_to_and_as_if_applicable: true

    # experimental features
    # collection_methods_unrelated_type: true

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options